### ISSUE TITLE
this code implement

### ISSUE THREAD

**Issue by xoceunder** [BYUI-Web/BYU-I-Roku-Channel#2]
this code implement

@jamesblack

**Comment by jamesblack** [comment]
I don't get it...

**Comment by xoceunder** [comment]
I have a job to do at an app for Roku want to make a new app you could do the job

@jamesblack

**Comment by SamJBarney** [comment]
See https://github.com/BYUI-Web/BYU-I-Roku-Channel/issues/3#issuecomment-113848169
